UniversDj\Model\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
    password:
      type: string
      nullable: true
    enabled:
      type: boolean
      default: true
    accountNonExpired:
      type: boolean
      default: true
    accountNonLocked:
      type: boolean
      default: true
    credentialsNonExpired:
      type: boolean
      default: true
    roles:
      type: array
      nullable: true
